services:

  web:
    build: .
    command: uvicorn src:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db


  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_DB=${DB_NAME}